### ISSUE TITLE
Must be from 35 ! 

### ISSUE THREAD

**Issue by proteck** [supervos/coda-parser#3]
https://github.com/supervos/coda-parser/blob/3ef415931dac9a297056f70bf651174a3d0df86b/CodaParser/LineParsers/IdentificationLineParser.cs#L26

**Comment by supervos** [comment]
Hello Proteck,

These starting numbers are 0-based while the documentation is 1-based.

If the documentation states that something starts at character 35, then the code must look at (35-1)=34.

I have double checked this with the documentation found at https://www.febelfin.be/sites/default/files/Standard-CODA-2.3-NL.pdf page 14.

Thank you for your interest in this project and your time creating this issue. I will close this issue but feel free to reopen it if you find other documentation or can create a test that proves that this needs fixing.
